name: DoodCore
version: 0.1.0
authors: [Dooder07]
website: http://doodcraft.net/
main: net.doodcraft.dooder07.spigot.doodcore.DoodCorePlugin
softdepend: [Vault, Protocollib]

commands:
  core:
    description: Base command
permissions:
  doodcore.admin:
    description: Parent node for administrators
    default: OP